version: "3.1"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: venn
      MYSQL_DATABASE: venn
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3306"]
      interval: 1s
      timeout: 1s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8090"

  backend:
    image: node:latest
    restart: always
    environment:
      NODE_ENV: development
      DB_NAME: venn
      DB_USER: root
      DB_PASSWORD: venn
      DB_HOST: mysql
      DB_DIALECT: mysql
      SERVER_PORT: 8080
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./Backend:/app
    working_dir: /app
    command: ["npm", "run", "start"]
    ports:
      - "8080:8080"
